const:
    home: /home/${env:USER}
    inf: 99999999999

log:
    dir: logs

model:
    input_shape: [64, 64, 3]
    n_discrete_actions: 3

agent:
    enabled_joints: [3]
    n_discrete_actions: 3
    max_buffer_size: 500
    vel_min: -0.001
    vel_max: 0.001

joint:
    start_eps: 0.15
    target_eps: 0.15
    bsize: 10
    alph: 0.95

env:
    env_path: ${const.home}/projects/curious_vrep/envs/test.ttt
    headless: True

trainer:
    video_len: 0

exp:
    train_iv: True
    train_fw: True
    train_policy: True
    train_after: 500
    video_after: ${const.inf}
    toggle_table_after: ${const.inf}
    n_episodes: 5000

hydra:
  run:
    dir: ./outputs/${log.dir}